// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./functions/LoadGitHubRaw.ts";
import * as $$$$$$0 from "./sections/Head.tsx";
import * as $$$$$$1 from "./sections/ContactCard.tsx";
import * as $$$$$$2 from "./sections/Banner.tsx";
import * as $$$$$$3 from "./sections/BannerText.tsx";
import * as $$$$$$4 from "./sections/GetStarted.tsx";
import * as $$$$$$5 from "./sections/Pacotes.tsx";
import * as $$$$$$6 from "./sections/OurWork.tsx";
import * as $$$$$$7 from "./sections/ContainerFlexRow.tsx";
import * as $$$$$$8 from "./sections/TextList.tsx";
import * as $$$$$$9 from "./sections/Footer.tsx";
import * as $$$$$$10 from "./sections/DesignSystem.tsx";
import * as $$$$$$11 from "./sections/Faq.tsx";
import * as $$$$$$12 from "./sections/Form.tsx";
import * as $$$$$$13 from "./sections/Header.tsx";
import * as $$$$$$14 from "./sections/ImageGallery.tsx";
import * as $$$$$$15 from "./sections/RichText.tsx";
import * as $$$$$$16 from "./sections/Testmonials.tsx";
import * as $$$$$$17 from "./sections/Instafeed.tsx";
import * as $$$$$$$$$$$0 from "./apps/site.ts";

const manifest = {
  "functions": {
    "deco-sites/buffetcabana/functions/LoadGitHubRaw.ts": $0,
  },
  "sections": {
    "deco-sites/buffetcabana/sections/Banner.tsx": $$$$$$2,
    "deco-sites/buffetcabana/sections/BannerText.tsx": $$$$$$3,
    "deco-sites/buffetcabana/sections/ContactCard.tsx": $$$$$$1,
    "deco-sites/buffetcabana/sections/ContainerFlexRow.tsx": $$$$$$7,
    "deco-sites/buffetcabana/sections/DesignSystem.tsx": $$$$$$10,
    "deco-sites/buffetcabana/sections/Faq.tsx": $$$$$$11,
    "deco-sites/buffetcabana/sections/Footer.tsx": $$$$$$9,
    "deco-sites/buffetcabana/sections/Form.tsx": $$$$$$12,
    "deco-sites/buffetcabana/sections/GetStarted.tsx": $$$$$$4,
    "deco-sites/buffetcabana/sections/Head.tsx": $$$$$$0,
    "deco-sites/buffetcabana/sections/Header.tsx": $$$$$$13,
    "deco-sites/buffetcabana/sections/ImageGallery.tsx": $$$$$$14,
    "deco-sites/buffetcabana/sections/Instafeed.tsx": $$$$$$17,
    "deco-sites/buffetcabana/sections/OurWork.tsx": $$$$$$6,
    "deco-sites/buffetcabana/sections/Pacotes.tsx": $$$$$$5,
    "deco-sites/buffetcabana/sections/RichText.tsx": $$$$$$15,
    "deco-sites/buffetcabana/sections/Testmonials.tsx": $$$$$$16,
    "deco-sites/buffetcabana/sections/TextList.tsx": $$$$$$8,
  },
  "apps": {
    "deco-sites/buffetcabana/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/buffetcabana",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
